import React from "react";
import type { DashboardWidgetSchema } from "../widgets/types";
import {
  HeroCard,
  MediaCarousel,
  AudioPlayer,
  VideoEmbed,
  ProductGrid,
  FlashcardDeck,
  QuizWidget,
  TimelineWidget,
  MarkdownPreview,
  ResearchPaperCard,
  NewsCard,
  MapWidget,
  TrendChart,
  CalendarWidget,
  ActionList,
  TabClusterMap,
  EmbeddedPreview,
  StatsPanel,
  ComparisonTable,
  RecommendationSlider,
} from "../widgets/components";

export const WIDGET_REGISTRY: Record<string, React.ComponentType<{ widget: DashboardWidgetSchema }>> = {
  hero: HeroCard,
  hero_card: HeroCard,
  media_carousel: MediaCarousel,
  audio: AudioPlayer,
  audio_player: AudioPlayer,
  video: VideoEmbed,
  video_embed: VideoEmbed,
  product_grid: ProductGrid,
  flashcard_deck: FlashcardDeck,
  quiz: QuizWidget,
  quiz_widget: QuizWidget,
  timeline: TimelineWidget,
  timeline_widget: TimelineWidget,
  markdown: MarkdownPreview,
  markdown_preview: MarkdownPreview,
  research_paper: ResearchPaperCard,
  research_paper_card: ResearchPaperCard,
  news: NewsCard,
  news_card: NewsCard,
  map: MapWidget,
  map_widget: MapWidget,
  trend_chart: TrendChart,
  calendar: CalendarWidget,
  calendar_widget: CalendarWidget,
  action_list: ActionList,
  tab_cluster_map: TabClusterMap,
  embedded_preview: EmbeddedPreview,
  stats_panel: StatsPanel,
  comparison_table: ComparisonTable,
  recommendation_slider: RecommendationSlider,
};
